spring:
  application:
    name: sell_buy
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521:xe}
    username: ${DB_USERNAME:your_username}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: oracle.jdbc.OracleDriver
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
  jpa:
    show-sql: false
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:your_access_key}
        secret-key: ${AWS_SECRET_KEY:your_secret_key}
      region:
        static: ${AWS_REGION:ap-northeast-1}
server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    session:
      cookie:
        name: JSESSIONID
      timeout: 30s
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
